live_config_reload = true

[colors]
draw_bold_text_with_bright_colors = true
transparent_background_colors = false

[colors.bright]
black = "#323232"
blue = "#5896FF"
cyan = "#87CFE4"
green = "#6DC9A6"
magenta = "#AA79D0"
red = "#FF4F58"
white = "#DFDFDF"
yellow = "#DFC16D"

[colors.cursor]
cursor = "#A277FF"
text = "CellForeground"

[colors.footer_bar]
background = "#A277FF"
foreground = "#000000"

[colors.normal]
black = "#323232"
blue = "#5896FF"
cyan = "#87CFE4"
green = "#6DC9A6"
magenta = "#AA79D0"
red = "#FF4F58"
white = "#DFDFDF"
yellow = "#DFC16D"

[colors.primary]
background = "#000000"
foreground = "#EEEEEE"

[colors.search.matches]
background = "#A277FF"
foreground = "CellBackground"

[colors.selection]
background = "#A277FF"
foreground = "#262626"
text = "CellForeground"

[cursor]
blink_interval = 750
unfocused_hollow = true

[cursor.style]
blinking = "On"
shape = "Block"

[font]
size = 12

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "ExtraLight"

[scrolling]
# auto_scroll = false
# faux_multiplier = 3
history = 1000
multiplier = 3

[selection]
save_to_clipboard = false

[shell]
args = ["-i", "--login"]
program = "/bin/zsh"

[window]
opacity = 0.8

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.dimensions]
columns = 180
lines = 40

[window.padding]
x = 15
y = 0
